### ISSUE TITLE
All bars no longer working

### ISSUE THREAD

**Issue by Lame-One** [0ceal0t/JobBars#38] opened 2021-08-20 16:27 UTC
Booted up FF today,  no job bars are being displayed.  They had previously worked without issue, as recently as yesterday. Verified with AST, DRG, and DNC.  Toggled all settings (enabled, hidden out of combat, split, etc) with no improvement. Additionally deleted the .json in pluginConfigs and uninstalled-reinstalled the plugin, again with no improvement.

**Comment by 0ceal0t** [comment] 2021-08-20 16:57
Can you attach your log (`dalamud.log` in `%appdata%\XIVLauncher\`)?

Also does the configuration menu appear when you use the `/jobbars` chat command?

**Comment by 0ceal0t** [comment] 2021-08-20 16:59
also, do you see the positioning window when you toggle "locked"?
![image](https://user-images.githubusercontent.com/18051158/130268269-ca19033a-4394-4e7a-a5e7-d833d92463cf.png)

**Comment by Lame-One** [comment] 2021-08-20 17:08
I do indeed see the positioning. I was concerned that it was just stuck off screen somehow at first, but that doesn't seem to be the case.  I also recently started using ZeffUI, but they were working fine together last night.  Attached is the requested log file.
[dalamud.log](https://github.com/0ceal0t/JobBars/files/7023105/dalamud.log)

**Comment by Lame-One** [comment] 2021-08-20 17:08
I do indeed have HP/MP bars hidden. Does that cause an issue?

**Comment by 0ceal0t** [comment] 2021-08-20 17:08
yes. try making them visible

**Comment by Lame-One** [comment] 2021-08-20 17:10
That seems to have fixed it.  Is this a bug, or expected behavior?

**Comment by 0ceal0t** [comment] 2021-08-20 17:12
it's unfortunately a limitation of how FFXIV's UI system works, so it's intended behavior. I'm trying to find a way around it, but for now you'll have to keep you HP/MP bar visible. I know some people make it really small and hide it behind their minimap

**Comment by 0ceal0t** [comment] 2021-08-20 17:13
Since this seems to be resolved though, I'll close this issue. Feel free to open up another one if you have any more questions or issues

**Closed by 0ceal0t** 2021-08-20 17:13 UTC

**Comment by Lame-One** [comment] 2021-08-20 17:16
If it has to be tied to an element, I recommend either using something like the chat box (that will be showing regardless of UI addons), or have an internal list of potential candidates that you go down to verify the opacity/visibility of, just to prevent this from popping up in the future.

Actually not sure if you can use the chat box, since it doesn't seem to act as an element like the rest, but if you could, that'd be even better since it literally can't be disabled.

Thanks a bunch!

**Comment by 0ceal0t** [comment] 2021-08-20 17:39
huh. using the chat box isn't a bad idea. I'll give that a shot

**Comment by 0ceal0t** [comment] 2021-08-20 17:52
yeah, looks like that works. Should be coming with the big endwalker update. thanks for the suggestion 👍
